/**
 * Modifier definitions aligned with `prisma/seed.ts` (S-01 calibration).
 * Used only by `full-stages-calibration.ts` — not imported by production code.
 */
export type CalibrationModifierDef = {
  stageSlug: string;
  triggerQuestionSlug: string;
  triggerValue: string;
  costAdjustmentPerM2: number;
  fixedCostAdjustment: number;
  description: string;
};

export const calibrationModifierDefs: CalibrationModifierDef[] = [
  {
    stageSlug: "insulation",
    triggerQuestionSlug: "insulation_level",
    triggerValue: "ENHANCED",
    costAdjustmentPerM2: 15,
    fixedCostAdjustment: 0,
    description:
      "[PERCENT:15] Wzmocnione ocieplenie — podwyższony standard izolacji",
  },
  {
    stageSlug: "foundations",
    triggerQuestionSlug: "insulation_level",
    triggerValue: "ENHANCED",
    costAdjustmentPerM2: 60,
    fixedCostAdjustment: 0,
    description:
      "[PERCENT:15] Wzmocnione ocieplenie — izolacja fundamentów i posadzki",
  },
  {
    stageSlug: "roof_structure",
    triggerQuestionSlug: "insulation_level",
    triggerValue: "ENHANCED",
    costAdjustmentPerM2: 30,
    fixedCostAdjustment: 0,
    description: "[PERCENT:15] Wzmocnione ocieplenie — ocieplenie stropu/dachu",
  },
  {
    stageSlug: "heating",
    triggerQuestionSlug: "insulation_level",
    triggerValue: "ENHANCED",
    costAdjustmentPerM2: 18,
    fixedCostAdjustment: 0,
    description:
      "[PERCENT:15] Wzmocnione ocieplenie — wyższe wymagania instalacji grzewczej",
  },
  {
    stageSlug: "insulation",
    triggerQuestionSlug: "insulation_level",
    triggerValue: "PASSIVE",
    costAdjustmentPerM2: 30,
    fixedCostAdjustment: 0,
    description: "[PERCENT:30] Ocieplenie pasywne — standard izolacji pasywnej",
  },
  {
    stageSlug: "foundations",
    triggerQuestionSlug: "insulation_level",
    triggerValue: "PASSIVE",
    costAdjustmentPerM2: 120,
    fixedCostAdjustment: 0,
    description:
      "[PERCENT:30] Ocieplenie pasywne — izolacja fundamentów i posadzki",
  },
  {
    stageSlug: "roof_structure",
    triggerQuestionSlug: "insulation_level",
    triggerValue: "PASSIVE",
    costAdjustmentPerM2: 60,
    fixedCostAdjustment: 0,
    description: "[PERCENT:30] Ocieplenie pasywne — ocieplenie stropu/dachu",
  },
  {
    stageSlug: "heating",
    triggerQuestionSlug: "insulation_level",
    triggerValue: "PASSIVE",
    costAdjustmentPerM2: 36,
    fixedCostAdjustment: 0,
    description: "[PERCENT:30] Ocieplenie pasywne — rekuperacja i pompa ciepła",
  },
  {
    stageSlug: "roof_structure",
    triggerQuestionSlug: "roof_type",
    triggerValue: "HIP",
    costAdjustmentPerM2: 0,
    fixedCostAdjustment: 0,
    description: "[PERCENT:25] Typ kopertowy — więźba",
  },
  {
    stageSlug: "roof_covering",
    triggerQuestionSlug: "roof_type",
    triggerValue: "HIP",
    costAdjustmentPerM2: 0,
    fixedCostAdjustment: 0,
    description: "[PERCENT:15] Typ kopertowy — krycie dachu",
  },
  {
    stageSlug: "roof_structure",
    triggerQuestionSlug: "roof_type",
    triggerValue: "MANSARD",
    costAdjustmentPerM2: 0,
    fixedCostAdjustment: 0,
    description: "[PERCENT:80] Dach mansardowy — więźba",
  },
  {
    stageSlug: "roof_covering",
    triggerQuestionSlug: "roof_type",
    triggerValue: "MANSARD",
    costAdjustmentPerM2: 0,
    fixedCostAdjustment: 0,
    description: "[PERCENT:20] Dach mansardowy — krycie dachu",
  },
  {
    stageSlug: "roof_structure",
    triggerQuestionSlug: "roof_type",
    triggerValue: "FLAT",
    costAdjustmentPerM2: 0,
    fixedCostAdjustment: -11520,
    description: "Dach płaski — uproszczona konstrukcja",
  },
  {
    stageSlug: "roof_covering",
    triggerQuestionSlug: "roof_type",
    triggerValue: "FLAT",
    costAdjustmentPerM2: 0,
    fixedCostAdjustment: 0,
    description: "[PERCENT:5] Dach płaski — krycie hydroizolacyjne",
  },
  {
    stageSlug: "heating",
    triggerQuestionSlug: "build_standard",
    triggerValue: "ECONOMY",
    costAdjustmentPerM2: 0,
    fixedCostAdjustment: 15300,
    description: "Kotłownia i źródło ciepła — standard ekonomiczny",
  },
  {
    stageSlug: "heating",
    triggerQuestionSlug: "build_standard",
    triggerValue: "STANDARD",
    costAdjustmentPerM2: 0,
    fixedCostAdjustment: 21250,
    description: "Kotłownia i źródło ciepła — standard standardowy",
  },
  {
    stageSlug: "heating",
    triggerQuestionSlug: "build_standard",
    triggerValue: "PREMIUM",
    costAdjustmentPerM2: 0,
    fixedCostAdjustment: 32300,
    description: "Kotłownia i źródło ciepła — standard premium (pompa ciepła)",
  },
  {
    stageSlug: "windows_doors",
    triggerQuestionSlug: "build_standard",
    triggerValue: "ECONOMY",
    costAdjustmentPerM2: 0,
    fixedCostAdjustment: 1500,
    description: "[PER_UNIT:window_count] Okno — standard ekonomiczny",
  },
  {
    stageSlug: "windows_doors",
    triggerQuestionSlug: "build_standard",
    triggerValue: "STANDARD",
    costAdjustmentPerM2: 0,
    fixedCostAdjustment: 2600,
    description: "[PER_UNIT:window_count] Okno — standard standardowy",
  },
  {
    stageSlug: "windows_doors",
    triggerQuestionSlug: "build_standard",
    triggerValue: "PREMIUM",
    costAdjustmentPerM2: 0,
    fixedCostAdjustment: 4200,
    description: "[PER_UNIT:window_count] Okno — standard premium",
  },
  {
    stageSlug: "windows_doors",
    triggerQuestionSlug: "build_standard",
    triggerValue: "ECONOMY",
    costAdjustmentPerM2: 0,
    fixedCostAdjustment: 2800,
    description:
      "[PER_UNIT:exterior_door_count] Drzwi zewnętrzne — standard ekonomiczny",
  },
  {
    stageSlug: "windows_doors",
    triggerQuestionSlug: "build_standard",
    triggerValue: "STANDARD",
    costAdjustmentPerM2: 0,
    fixedCostAdjustment: 7200,
    description:
      "[PER_UNIT:exterior_door_count] Drzwi zewnętrzne — standard standardowy",
  },
  {
    stageSlug: "windows_doors",
    triggerQuestionSlug: "build_standard",
    triggerValue: "PREMIUM",
    costAdjustmentPerM2: 0,
    fixedCostAdjustment: 7800,
    description:
      "[PER_UNIT:exterior_door_count] Drzwi zewnętrzne — standard premium",
  },
  {
    stageSlug: "windows_doors",
    triggerQuestionSlug: "build_standard",
    triggerValue: "ECONOMY",
    costAdjustmentPerM2: 0,
    fixedCostAdjustment: 3200,
    description:
      "[PER_UNIT:terrace_door_count] Drzwi tarasowe — balkonowe zwykłe",
  },
  {
    stageSlug: "windows_doors",
    triggerQuestionSlug: "build_standard",
    triggerValue: "STANDARD",
    costAdjustmentPerM2: 0,
    fixedCostAdjustment: 11000,
    description:
      "[PER_UNIT:terrace_door_count] Drzwi tarasowe — przesuwne system smart",
  },
  {
    stageSlug: "windows_doors",
    triggerQuestionSlug: "build_standard",
    triggerValue: "PREMIUM",
    costAdjustmentPerM2: 0,
    fixedCostAdjustment: 15000,
    description: "[PER_UNIT:terrace_door_count] Drzwi tarasowe — przesuwne system HS",
  },
  {
    stageSlug: "floor_slabs",
    triggerQuestionSlug: "build_standard",
    triggerValue: "ECONOMY",
    costAdjustmentPerM2: 0,
    fixedCostAdjustment: 9000,
    description: "[PER_UNIT:balcony_count] Balkon — standard ekonomiczny",
  },
  {
    stageSlug: "floor_slabs",
    triggerQuestionSlug: "build_standard",
    triggerValue: "STANDARD",
    costAdjustmentPerM2: 0,
    fixedCostAdjustment: 15000,
    description: "[PER_UNIT:balcony_count] Balkon — standard standardowy",
  },
  {
    stageSlug: "floor_slabs",
    triggerQuestionSlug: "build_standard",
    triggerValue: "PREMIUM",
    costAdjustmentPerM2: 0,
    fixedCostAdjustment: 22000,
    description: "[PER_UNIT:balcony_count] Balkon — standard premium",
  },
  {
    stageSlug: "garage_gate",
    triggerQuestionSlug: "insulation_level",
    triggerValue: "STANDARD",
    costAdjustmentPerM2: 0,
    fixedCostAdjustment: 12000,
    description: "Brama garażowa — izolacja standardowa",
  },
  {
    stageSlug: "garage_gate",
    triggerQuestionSlug: "insulation_level",
    triggerValue: "ENHANCED",
    costAdjustmentPerM2: 0,
    fixedCostAdjustment: 14000,
    description: "Brama garażowa — podwyższona izolacja",
  },
  {
    stageSlug: "garage_gate",
    triggerQuestionSlug: "insulation_level",
    triggerValue: "PASSIVE",
    costAdjustmentPerM2: 0,
    fixedCostAdjustment: 16000,
    description: "Brama garażowa — klasa pasywna",
  },
  {
    stageSlug: "floor_slabs",
    triggerQuestionSlug: "has_attic",
    triggerValue: "true",
    costAdjustmentPerM2: 75,
    fixedCostAdjustment: 0,
    description: "Poddasze użytkowe — wzmocnienie stropu i schody wewnętrzne",
  },
  {
    stageSlug: "walls",
    triggerQuestionSlug: "floors",
    triggerValue: "2",
    costAdjustmentPerM2: 80,
    fixedCostAdjustment: 0,
    description: "Budynek dwukondygnacyjny — dodatkowa kondygnacja ścian",
  },
  {
    stageSlug: "walls",
    triggerQuestionSlug: "floors",
    triggerValue: "3",
    costAdjustmentPerM2: 150,
    fixedCostAdjustment: 0,
    description: "Budynek trzykondygnacyjny — dwie dodatkowe kondygnacje ścian",
  },
  {
    stageSlug: "floor_slabs",
    triggerQuestionSlug: "floors",
    triggerValue: "2",
    costAdjustmentPerM2: 70,
    fixedCostAdjustment: 0,
    description: "Dodatkowy strop międzykondygnacyjny",
  },
  {
    stageSlug: "floor_slabs",
    triggerQuestionSlug: "floors",
    triggerValue: "3",
    costAdjustmentPerM2: 140,
    fixedCostAdjustment: 0,
    description: "Dwa dodatkowe stropy międzykondygnacyjne",
  },

  // S-05 utility connections (Std PLN flat)
  {
    stageSlug: "sewage_connection",
    triggerQuestionSlug: "sewage_disposal",
    triggerValue: "MUNICIPAL",
    costAdjustmentPerM2: 0,
    fixedCostAdjustment: 12000,
    description: "Przyłącze kanalizacji gminnej",
  },
  {
    stageSlug: "sewage_connection",
    triggerQuestionSlug: "sewage_disposal",
    triggerValue: "SEPTIC_TANK",
    costAdjustmentPerM2: 0,
    fixedCostAdjustment: 7500,
    description: "Szambo betonowe z montażem",
  },
  {
    stageSlug: "sewage_connection",
    triggerQuestionSlug: "sewage_disposal",
    triggerValue: "TREATMENT_PLANT",
    costAdjustmentPerM2: 0,
    fixedCostAdjustment: 17500,
    description: "Przydomowa oczyszczalnia ścieków z montażem",
  },
  {
    stageSlug: "water_connection",
    triggerQuestionSlug: "water_supply",
    triggerValue: "MUNICIPAL",
    costAdjustmentPerM2: 0,
    fixedCostAdjustment: 8000,
    description: "Przyłącze wodociągu gminnego",
  },
  {
    stageSlug: "water_connection",
    triggerQuestionSlug: "water_supply",
    triggerValue: "WELL",
    costAdjustmentPerM2: 0,
    fixedCostAdjustment: 22000,
    description: "Studnia głębinowa z montażem (odwiert, pompa)",
  },
  {
    stageSlug: "sewage_connection",
    triggerQuestionSlug: "utility_distance_band",
    triggerValue: "UP_TO_50M",
    costAdjustmentPerM2: 0,
    fixedCostAdjustment: 0,
    description: "Odległość do sieci kanalizacyjnej — do 50 m (w bazie)",
  },
  {
    stageSlug: "sewage_connection",
    triggerQuestionSlug: "utility_distance_band",
    triggerValue: "UP_TO_100M",
    costAdjustmentPerM2: 0,
    fixedCostAdjustment: 4000,
    description: "Odległość do sieci kanalizacyjnej — add-on 51–100 m",
  },
  {
    stageSlug: "sewage_connection",
    triggerQuestionSlug: "utility_distance_band",
    triggerValue: "UP_TO_200M",
    costAdjustmentPerM2: 0,
    fixedCostAdjustment: 7000,
    description: "Odległość do sieci kanalizacyjnej — add-on 101–200 m",
  },
  {
    stageSlug: "sewage_connection",
    triggerQuestionSlug: "utility_distance_band",
    triggerValue: "OVER_200M",
    costAdjustmentPerM2: 0,
    fixedCostAdjustment: 12000,
    description: "Odległość do sieci kanalizacyjnej — add-on powyżej 200 m",
  },
  {
    stageSlug: "water_connection",
    triggerQuestionSlug: "utility_distance_band",
    triggerValue: "UP_TO_50M",
    costAdjustmentPerM2: 0,
    fixedCostAdjustment: 0,
    description: "Odległość do sieci wodociągowej — do 50 m (w bazie)",
  },
  {
    stageSlug: "water_connection",
    triggerQuestionSlug: "utility_distance_band",
    triggerValue: "UP_TO_100M",
    costAdjustmentPerM2: 0,
    fixedCostAdjustment: 4000,
    description: "Odległość do sieci wodociągowej — add-on 51–100 m",
  },
  {
    stageSlug: "water_connection",
    triggerQuestionSlug: "utility_distance_band",
    triggerValue: "UP_TO_200M",
    costAdjustmentPerM2: 0,
    fixedCostAdjustment: 7000,
    description: "Odległość do sieci wodociągowej — add-on 101–200 m",
  },
  {
    stageSlug: "water_connection",
    triggerQuestionSlug: "utility_distance_band",
    triggerValue: "OVER_200M",
    costAdjustmentPerM2: 0,
    fixedCostAdjustment: 12000,
    description: "Odległość do sieci wodociągowej — add-on powyżej 200 m",
  },
];
